exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

plugins:
- jekyll-sitemap
#- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

paginate: 5 # jekyll-paginate > items per page
paginate_path: posts/page:num # jekyll-paginate > blog page

#jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
#twitter:
#  username: # jekyll-seo-tag > Owners twitter username

author: JWHer
social:
  name: JWHer
  links:
#    - https://twitter.com/DavidDarnes
#    - https://www.facebook.com/daviddarnes
    - https://www.linkedin.com/in/정원-허-1160b3193
    - https://github.com/jwher

#markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
#commonmark:
#  options: ["SMART", "FOOTNOTES"]
#  extensions: ["strikethrough", "autolink", "table"]

sass:
  style: compressed
permalink: /:title # Permalink style (pretty: /YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: # Timezone for blog posts and alike

collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "생각과 아이디어" # The post list page content
    feature_text: |
      Let thine heart retain my words:
      Keep my commandments, and live.
    feature_image: /assets/Bamboo-road.jpg

defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# Site settings
encoding: utf-8
lang: ko
title: "허정원 기술블로그"
logo: "/assets/logos/logo.svg"
description: "I hang out with some ML, Using kubernetes-kubeflow"
url: "https://jwher.github.io"
baseurl: ""
repo: "https://github.com/jwher/jwher.github.io"
email: "hacell2@gmail.com"
disqus: "jwher"
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
google_analytics: "G-XHBVCY40VB"
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo.svg'
  32: '/assets/logos/logo.svg'
  96: '/assets/logos/logo.svg'
  120: '/assets/logos/logo.svg'
  144: '/assets/logos/logo.svg'
  180: '/assets/logos/logo.svg'
  512: '/assets/logos/logo.svg'
  1024: '/assets/logos/logo.svg'

# --- 네비게이션 --- #
navigation_header:
- title: Home
  url: /
#- title: Elements
#  url: /elements/
- title: Posts
  url: /posts/
- title: Categories
  url: /categories
#- title: ⌕
#  url: /search/
#- title: Fork Alembic
#  url: https://github.com/daviddarnes/alembic

navigation_footer:
- title: Created by JWHer
  url: https://github.com/jwher

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
#  Twitter: https://twitter.com/DavidDarnes
  LinkedIn: https://www.linkedin.com/in/정원-허-1160b3193
  GitHub: https://github.com/jwher
#  link: https://darn.es
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
#  Twitter: "#0d94e7"
#  facebook: "#3B5998"
  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
    - https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap

live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: hijiki
  display:
    position: right
    width: 150
    height: 150
  mobile:
    show: true
