// AUTO-GENERATED by scripts/generate-content-index.js
// DO NOT EDIT MANUALLY — regenerated on every `npm run build` and `npm run start`

export type ContentItem = {
  title: string;
  path: string;
  description: string;
  tags: string[];
  keywords: string[];
  date?: string;
  image?: string;
};

export const CONTENT_INDEX: ContentItem[] = [
  {
    "title": "ChatGPT: 부와 신앙의 이중성에 대해",
    "path": "/blog/chatgpt-duality-of-wealth-and-faith",
    "description": "Zior Park 크리스쳔 가사에 대한 고찰",
    "tags": [
      "tech",
      "theology"
    ],
    "keywords": [
      "chatgpt",
      "duality",
      "of",
      "wealth",
      "and",
      "faith"
    ],
    "date": "2023-05-21",
    "image": "/img/logos/chatgpt.png"
  },
  {
    "title": "지도자의 부르심",
    "path": "/blog/discipleship-training-1",
    "description": "새싹목자훈련 1주차",
    "tags": [
      "theology"
    ],
    "keywords": [
      "discipleship",
      "training",
      "1"
    ],
    "date": "2023-04-01"
  },
  {
    "title": "GitHub Sponsors 시작하기",
    "path": "/blog/github-sponsors",
    "description": "GitHub Sponsors 시작하기 - 오픈소스 후원 문화",
    "tags": [
      "github",
      "opensource",
      "funding"
    ],
    "keywords": [
      "github",
      "sponsors"
    ],
    "date": "2022-07-28",
    "image": "/img/logos/github.svg"
  },
  {
    "title": "Nmap - 네트워크 스캐닝 도구 완전 가이드",
    "path": "/blog/nmap",
    "description": "Nmap 네트워크 스캐너 사용법과 옵션 가이드",
    "tags": [
      "network",
      "security",
      "tools",
      "linux"
    ],
    "keywords": [
      "nmap"
    ],
    "date": "2022-07-12"
  },
  {
    "title": "M1 Mac에서 PyTorch GPU 가속 활용하기",
    "path": "/blog/pytorch-in-m1",
    "description": "M1 Mac에서 PyTorch GPU 가속 사용하기 - Metal Performance Shaders로 최대 500% 성능 향상",
    "tags": [
      "pytorch",
      "m1",
      "apple-silicon",
      "machine-learning",
      "gpu"
    ],
    "keywords": [
      "pytorch",
      "in",
      "m1"
    ],
    "date": "2022-06-12"
  },
  {
    "title": "First post with docusaurus",
    "path": "/blog/first-post-with-docusaurus",
    "description": "Jekyll에서 Docusaurus로 블로그 마이그레이션 - 더 나은 문서화를 위한 선택",
    "tags": [
      "blog",
      "docusaurus"
    ],
    "keywords": [
      "first",
      "post",
      "with",
      "docusaurus"
    ],
    "date": "2022-05-30"
  },
  {
    "title": "Blog Tech Map",
    "path": "/blog/blog-tech-map",
    "description": "허정원 기술블로그",
    "tags": [
      "blog",
      "tech"
    ],
    "keywords": [
      "blog",
      "tech",
      "map"
    ],
    "date": "2021-08-23",
    "image": "/img/logo.svg"
  },
  {
    "title": "CNCF - 클라우드 네이티브 컴퓨팅 재단",
    "path": "/blog/cncf",
    "description": "CNCF: Cloud Native Computing Foundation - 클라우드 네이티브 컴퓨팅 재단",
    "tags": [
      "kubernetes",
      "cloud-native",
      "opensource",
      "cncf"
    ],
    "keywords": [
      "cncf"
    ],
    "date": "2021-08-23",
    "image": "/img/logos/cncf.svg"
  },
  {
    "title": "Free Wildcard Dns",
    "path": "/blog/free-wildcard-dns",
    "description": "무료 와일드카드 DNS",
    "tags": [
      "dev",
      "short"
    ],
    "keywords": [
      "free",
      "wildcard",
      "dns"
    ],
    "date": "2021-07-21",
    "image": "/img/wildcard.svg"
  },
  {
    "title": "기술 블로그 운영 회고 - 나에게 필요한 연재",
    "path": "/blog/blog-essay",
    "description": "기술 블로그 운영 회고와 개선 방향",
    "tags": [
      "blog",
      "retrospective"
    ],
    "keywords": [
      "blog",
      "essay"
    ],
    "date": "2021-05-27",
    "image": "/img/pen.svg"
  },
  {
    "title": "지킬 블로그 업데이트",
    "path": "/blog/update-blog",
    "description": "Update Blog",
    "tags": [
      "blog",
      "update"
    ],
    "keywords": [
      "update",
      "blog"
    ],
    "date": "2021-05-23"
  },
  {
    "title": "Jekyll로 시작하는 첫 포스트",
    "path": "/blog/first-post",
    "description": "Jekyll로 시작하는 기술 블로그",
    "tags": [
      "blog",
      "jekyll"
    ],
    "keywords": [
      "first",
      "post"
    ],
    "date": "2021-04-11"
  },
  {
    "title": "7가지 동시성 모델(소개)",
    "path": "/docs/development/concurrency/concurrency-models-1",
    "description": "Seven Concurrency Models in Seven Weeks - Chapter1",
    "tags": [
      "concurrency",
      "parallelism",
      "theory"
    ],
    "keywords": [
      "development",
      "concurrency",
      "models",
      "1"
    ]
  },
  {
    "title": "7가지 동시성 모델(스레드와 락) 거인의 어깨 위에서",
    "path": "/docs/development/concurrency/concurrency-models-4",
    "description": "Seven Concurrency Models in Seven Weeks - Chapter2 Day3",
    "tags": [
      "concurrency",
      "parallelism",
      "theory"
    ],
    "keywords": [
      "development",
      "concurrency",
      "models",
      "4"
    ]
  },
  {
    "title": "7가지 동시성 모델(스레드와 락) 고유 락 개선하기",
    "path": "/docs/development/concurrency/concurrency-models-3",
    "description": "Seven Concurrency Models in Seven Weeks - Chapter2 Day2",
    "tags": [
      "concurrency",
      "parallelism",
      "theory"
    ],
    "keywords": [
      "development",
      "concurrency",
      "models",
      "3"
    ]
  },
  {
    "title": "7가지 동시성 모델(스레드와 락) 상호 배제와 메모리 모델",
    "path": "/docs/development/concurrency/concurrency-models-2",
    "description": "Seven Concurrency Models in Seven Weeks - Chapter2 Day1",
    "tags": [
      "concurrency",
      "parallelism",
      "theory"
    ],
    "keywords": [
      "development",
      "concurrency",
      "models",
      "2"
    ]
  },
  {
    "title": "가상 메모리 디자인",
    "path": "/docs/cs/computer-architecture/virtual-memory-design",
    "description": "Virtual Memory Design",
    "tags": [
      "cs",
      "computer architecture"
    ],
    "keywords": [
      "cs",
      "computer",
      "architecture",
      "virtual",
      "memory",
      "design"
    ]
  },
  {
    "title": "가속기 디자인",
    "path": "/docs/cs/computer-architecture/roofline-visual-performance-model",
    "description": "가속기",
    "tags": [
      "cs",
      "computer architecture"
    ],
    "keywords": [
      "cs",
      "computer",
      "architecture",
      "roofline",
      "visual",
      "performance",
      "model"
    ]
  },
  {
    "title": "강화학습",
    "path": "/docs/ml/reinforcement-learning",
    "description": "Reinforcement Learning",
    "tags": [
      "ml"
    ],
    "keywords": [
      "ml",
      "reinforcement",
      "learning"
    ]
  },
  {
    "title": "구글 TPU",
    "path": "/docs/cs/computer-architecture/google-tpu-v1",
    "description": "하드웨어 레벨의 병렬화",
    "tags": [
      "cs",
      "computer architecture"
    ],
    "keywords": [
      "cs",
      "computer",
      "architecture",
      "google",
      "tpu",
      "v1"
    ]
  },
  {
    "title": "근사를 통한 가속",
    "path": "/docs/ml/embedded-deep-learning/software/approximation",
    "description": "Acceleration By Approximation",
    "tags": [
      "cs",
      "ml"
    ],
    "keywords": [
      "ml",
      "embedded",
      "deep",
      "learning",
      "software",
      "approximation"
    ]
  },
  {
    "title": "근사를 통한 on-policy 예측",
    "path": "/docs/ml/reinforcement-learning/on-policy-prediction-with-approximation",
    "description": "On-policy Prediction with Approximation",
    "tags": [
      "ml",
      "rl"
    ],
    "keywords": [
      "ml",
      "reinforcement",
      "learning",
      "on",
      "policy",
      "prediction",
      "with",
      "approximation"
    ]
  },
  {
    "title": "근사를 통한 on-policy 제어",
    "path": "/docs/ml/reinforcement-learning/on-policy-control-with-approximation",
    "description": "On-policy Control with Approximation",
    "tags": [
      "ml",
      "rl"
    ],
    "keywords": [
      "ml",
      "reinforcement",
      "learning",
      "on",
      "policy",
      "control",
      "with",
      "approximation"
    ]
  },
  {
    "title": "나에게 필요한 도커 설치하기",
    "path": "/docs/infrastructure/containerization/install-docker",
    "description": "Install Docker",
    "tags": [
      "docker",
      "containerization",
      "tutorial",
      "installation"
    ],
    "keywords": [
      "infrastructure",
      "containerization",
      "install",
      "docker"
    ]
  },
  {
    "title": "나에게 필요한 쿠버네티스 설치하기",
    "path": "/docs/infrastructure/kubernetes/install-kubernetes",
    "description": "Install Kubernetes",
    "tags": [
      "kubernetes",
      "installation",
      "tutorial"
    ],
    "keywords": [
      "infrastructure",
      "kubernetes",
      "install"
    ]
  },
  {
    "title": "다시보는 동시성프로그래밍",
    "path": "/docs/development/concurrency/concurrent-programming",
    "description": "분산처리시스템과 고성능 클러스터",
    "tags": [
      "cs"
    ],
    "keywords": [
      "development",
      "concurrency",
      "concurrent",
      "programming"
    ]
  },
  {
    "title": "다시보는 컴퓨터구조1",
    "path": "/docs/foundations/computer-architecture",
    "description": "컴퓨터의 작동원리",
    "tags": [
      "cs"
    ],
    "keywords": [
      "foundations",
      "computer",
      "architecture"
    ]
  },
  {
    "title": "다양한 급수",
    "path": "/docs/foundations/mathematics/power-series",
    "description": "다양한 급수",
    "tags": [
      "mathematics",
      "calculus",
      "theory"
    ],
    "keywords": [
      "foundations",
      "mathematics",
      "power",
      "series"
    ]
  },
  {
    "title": "다이나믹 프로그래밍",
    "path": "/docs/ml/reinforcement-learning/dynamic-programming",
    "description": "Dynamic Programming",
    "tags": [
      "ml",
      "rl",
      "reinforcement"
    ],
    "keywords": [
      "ml",
      "reinforcement",
      "learning",
      "dynamic",
      "programming"
    ]
  },
  {
    "title": "대규모 병렬프로세서 프로그래밍(소개)",
    "path": "/docs/development/languages/programming-massively-parallel-processors",
    "description": "Programming Massively Parallel Processors - Chapter 1",
    "tags": [
      "cuda",
      "gpu",
      "parallel-computing",
      "tutorial"
    ],
    "keywords": [
      "development",
      "languages",
      "programming",
      "massively",
      "parallel",
      "processors"
    ]
  },
  {
    "title": "데이터 수준 병렬화",
    "path": "/docs/cs/computer-architecture/data-level-parallelism",
    "description": "Data Level Parallelism",
    "tags": [
      "cs",
      "computer architecture"
    ],
    "keywords": [
      "cs",
      "computer",
      "architecture",
      "data",
      "level",
      "parallelism"
    ]
  },
  {
    "title": "데이터 스트리밍 알고리즘",
    "path": "/docs/algorithms/07_data_streaming",
    "description": "대규모 데이터 처리를 위한 스트리밍 모델과 알고리즘",
    "tags": [],
    "keywords": [
      "algorithms",
      "07",
      "data",
      "streaming"
    ]
  },
  {
    "title": "도메인에 맞는 아키텍처",
    "path": "/docs/cs/computer-architecture/domain-specific-architecture",
    "description": "asic",
    "tags": [
      "cs",
      "computer architecture"
    ],
    "keywords": [
      "cs",
      "computer",
      "architecture",
      "domain",
      "specific"
    ]
  },
  {
    "title": "도커 네트워킹",
    "path": "/docs/infrastructure/containerization/docker-networking",
    "description": "도커 딥 다이브",
    "tags": [
      "docker",
      "containerization",
      "networking"
    ],
    "keywords": [
      "infrastructure",
      "containerization",
      "docker",
      "networking"
    ]
  },
  {
    "title": "도커 엔진",
    "path": "/docs/infrastructure/containerization/the-docker-engine",
    "description": "도커 딥 다이브",
    "tags": [
      "docker",
      "containerization",
      "architecture"
    ],
    "keywords": [
      "infrastructure",
      "containerization",
      "the",
      "docker",
      "engine"
    ]
  },
  {
    "title": "마르코프 결정 과정",
    "path": "/docs/ml/reinforcement-learning/markov-decision-process",
    "description": "Markov Decision Process",
    "tags": [
      "ml"
    ],
    "keywords": [
      "ml",
      "reinforcement",
      "learning",
      "markov",
      "decision",
      "process"
    ]
  },
  {
    "title": "머신러닝에 숨은 기술 부채",
    "path": "/docs/machine-learning/research-papers/hidden-technical-debt",
    "description": "Hidden Technical Debt in Machine Learning Systems",
    "tags": [
      "machine-learning",
      "mlops",
      "best-practices",
      "research"
    ],
    "keywords": [
      "machine",
      "learning",
      "research",
      "papers",
      "hidden",
      "technical",
      "debt"
    ]
  },
  {
    "title": "메모리 계층 디자인",
    "path": "/docs/cs/computer-architecture/memory-hierarchy-design",
    "description": "Memory Hierarchy Design",
    "tags": [
      "cs",
      "computer architecture"
    ],
    "keywords": [
      "cs",
      "computer",
      "architecture",
      "memory",
      "hierarchy",
      "design"
    ]
  },
  {
    "title": "명령어 수준 병렬화",
    "path": "/docs/cs/computer-architecture/instruction-level-parallelism",
    "description": "Instruction Level Parallelism",
    "tags": [
      "cs",
      "computer architecture"
    ],
    "keywords": [
      "cs",
      "computer",
      "architecture",
      "instruction",
      "level",
      "parallelism"
    ]
  },
  {
    "title": "몬테 카를로 방법",
    "path": "/docs/ml/reinforcement-learning/monte-carlo-methods",
    "description": "Monte Carlo Methods",
    "tags": [
      "ml"
    ],
    "keywords": [
      "ml",
      "reinforcement",
      "learning",
      "monte",
      "carlo",
      "methods"
    ]
  },
  {
    "title": "소개",
    "path": "/docs/cs/digital-system-design-methodology/intro",
    "description": "디지털 시스템 설계방법론 - 소개",
    "tags": [
      "cs"
    ],
    "keywords": [
      "cs",
      "digital",
      "system",
      "design",
      "methodology",
      "intro"
    ]
  },
  {
    "title": "시간차 학습",
    "path": "/docs/ml/reinforcement-learning/temporal-difference-learning",
    "description": "Temporal-Difference Learning",
    "tags": [
      "ml",
      "rl"
    ],
    "keywords": [
      "ml",
      "reinforcement",
      "learning",
      "temporal",
      "difference"
    ]
  },
  {
    "title": "실시간시스템",
    "path": "/docs/cs/real-time-system/definition",
    "description": "실시간 시스템 - 정의",
    "tags": [
      "cs"
    ],
    "keywords": [
      "cs",
      "real",
      "time",
      "system",
      "definition"
    ]
  },
  {
    "title": "실시간시스템",
    "path": "/docs/cs/real-time-system/fixed-priority1",
    "description": "실시간 시스템 - 고정된 우선순위",
    "tags": [
      "cs"
    ],
    "keywords": [
      "cs",
      "real",
      "time",
      "system",
      "fixed",
      "priority1"
    ]
  },
  {
    "title": "실시간시스템",
    "path": "/docs/cs/real-time-system/thread",
    "description": "실시간 시스템 - 스레드",
    "tags": [
      "cs"
    ],
    "keywords": [
      "cs",
      "real",
      "time",
      "system",
      "thread"
    ]
  },
  {
    "title": "실시간시스템",
    "path": "/docs/cs/real-time-system/worst-case-execution-time",
    "description": "실시간 시스템 - 최악 실행 시간 분석",
    "tags": [
      "cs"
    ],
    "keywords": [
      "cs",
      "real",
      "time",
      "system",
      "worst",
      "case",
      "execution"
    ]
  },
  {
    "title": "실시간시스템",
    "path": "/docs/cs/real-time-system/aperiodic",
    "description": "실시간 시스템 - 우선순의 기반 시스템에서 비주기적 스케줄링",
    "tags": [
      "cs"
    ],
    "keywords": [
      "cs",
      "real",
      "time",
      "system",
      "aperiodic"
    ]
  },
  {
    "title": "쓰레드 수준 병렬화",
    "path": "/docs/cs/computer-architecture/thread-level-parallelism",
    "description": "Thread Level Parallelism",
    "tags": [
      "cs",
      "computer architecture"
    ],
    "keywords": [
      "cs",
      "computer",
      "architecture",
      "thread",
      "level",
      "parallelism"
    ]
  },
  {
    "title": "여러대의 슬롯머신",
    "path": "/docs/ml/reinforcement-learning/multi-armed-bandits",
    "description": "Multi-armed Bandits",
    "tags": [
      "ml",
      "rl"
    ],
    "keywords": [
      "ml",
      "reinforcement",
      "learning",
      "multi",
      "armed",
      "bandits"
    ]
  },
  {
    "title": "오래걸리는 API 설계",
    "path": "/docs/development/web/api-design-for-long-jobs",
    "description": "오래걸리는 API 설계",
    "tags": [
      "api",
      "web",
      "architecture",
      "best-practices"
    ],
    "keywords": [
      "development",
      "web",
      "api",
      "design",
      "for",
      "long",
      "jobs"
    ]
  },
  {
    "title": "요구사항에 사용하는 RFC 키워드",
    "path": "/docs/infrastructure/kubernetes/requirement-levels",
    "description": "Key words for use in RFCs to Indicate Requirement Levels",
    "tags": [
      "kubernetes",
      "best-practices"
    ],
    "keywords": [
      "infrastructure",
      "kubernetes",
      "requirement",
      "levels"
    ]
  },
  {
    "title": "운영체제의 개요",
    "path": "/docs/foundations/linux/linux-overview",
    "description": "Linux overview",
    "tags": [
      "linux"
    ],
    "keywords": [
      "foundations",
      "linux",
      "overview"
    ]
  },
  {
    "title": "유클리드 호제법",
    "path": "/docs/foundations/mathematics/euclidean-algorithm",
    "description": "최대공약수와 최소공배수를 구하는 방법",
    "tags": [
      "mathematics",
      "algorithms",
      "theory"
    ],
    "keywords": [
      "foundations",
      "mathematics",
      "euclidean",
      "algorithm"
    ]
  },
  {
    "title": "이항정리 - π값을 구하는 법",
    "path": "/docs/foundations/mathematics/binomial-theorem",
    "description": "Binomial Theorem",
    "tags": [
      "mathematics",
      "calculus",
      "theory"
    ],
    "keywords": [
      "foundations",
      "mathematics",
      "binomial",
      "theorem"
    ]
  },
  {
    "title": "임베디드 딥러닝",
    "path": "/docs/machine-learning/deep-learning/embedded-deep-learning",
    "description": "하드웨어 소프트웨어 통합 설계와 병렬 처리",
    "tags": [
      "cs",
      "ml"
    ],
    "keywords": [
      "machine",
      "learning",
      "deep",
      "embedded"
    ]
  },
  {
    "title": "임베디드 딥러닝",
    "path": "/docs/ml/embedded-deep-learning/hardware",
    "description": "하드웨어 가속 기술",
    "tags": [
      "cs",
      "ml"
    ],
    "keywords": [
      "ml",
      "embedded",
      "deep",
      "learning",
      "hardware"
    ]
  },
  {
    "title": "임베디드 딥러닝",
    "path": "/docs/ml/embedded-deep-learning",
    "description": "임베디드 딥러닝 강의 노트",
    "tags": [
      "ml",
      "embedded",
      "deep-learning"
    ],
    "keywords": [
      "ml",
      "embedded",
      "deep",
      "learning"
    ]
  },
  {
    "title": "자주쓰는 쿠버네티스 명령어",
    "path": "/docs/infrastructure/kubernetes/kubernetes-usage",
    "description": "Kubernetes Usage",
    "tags": [
      "kubernetes",
      "tutorial",
      "quick-reference"
    ],
    "keywords": [
      "infrastructure",
      "kubernetes",
      "usage"
    ]
  },
  {
    "title": "적격자 추적",
    "path": "/docs/ml/reinforcement-learning/eligibility-trace",
    "description": "Eligibility Traces",
    "tags": [
      "ml",
      "rl",
      "reinforcement"
    ],
    "keywords": [
      "ml",
      "reinforcement",
      "learning",
      "eligibility",
      "trace"
    ]
  },
  {
    "title": "정책 기울기 방법들",
    "path": "/docs/ml/reinforcement-learning/policy-gradient-methods",
    "description": "Policy Gradient Methods",
    "tags": [
      "ml",
      "rl",
      "reinforcement"
    ],
    "keywords": [
      "ml",
      "reinforcement",
      "learning",
      "policy",
      "gradient",
      "methods"
    ]
  },
  {
    "title": "정확한 추론을 위한 양자화 기법",
    "path": "/docs/machine-learning/deep-learning/quantization",
    "description": "양자화를 통한 딥러닝 모델 경량화",
    "tags": [
      "machine-learning",
      "deep-learning",
      "optimization"
    ],
    "keywords": [
      "machine",
      "learning",
      "deep",
      "quantization"
    ]
  },
  {
    "title": "컴퓨터 구조",
    "path": "/docs/cs/computer-architecture",
    "description": "컴퓨터 구조 강의 노트",
    "tags": [
      "cs",
      "computer architecture"
    ],
    "keywords": [
      "cs",
      "computer",
      "architecture"
    ]
  },
  {
    "title": "코딩 기초 트레이닝1",
    "path": "/docs/development/languages/cpp-coding-basic1",
    "description": "C/C++ 재활 훈련",
    "tags": [
      "cpp",
      "c++",
      "tutorial",
      "basics"
    ],
    "keywords": [
      "development",
      "languages",
      "cpp",
      "coding",
      "basic1"
    ]
  },
  {
    "title": "코딩 기초 트레이닝2",
    "path": "/docs/development/languages/cpp-coding-basic2",
    "description": "C/C++ 재활 훈련",
    "tags": [
      "cpp",
      "c++",
      "tutorial",
      "basics"
    ],
    "keywords": [
      "development",
      "languages",
      "cpp",
      "coding",
      "basic2"
    ]
  },
  {
    "title": "쿠버네티스 기본 개념과 필요성",
    "path": "/docs/infrastructure/kubernetes/welcome-to-kubernetes",
    "description": "Welcome To Kubernetes",
    "tags": [
      "kubernetes",
      "containerization",
      "introduction"
    ],
    "keywords": [
      "infrastructure",
      "kubernetes",
      "welcome",
      "to"
    ]
  },
  {
    "title": "쿠버네티스 아키텍처",
    "path": "/docs/infrastructure/kubernetes/kubernetes-architecture",
    "description": "Kubernetes Architecture",
    "tags": [
      "kubernetes",
      "architecture"
    ],
    "keywords": [
      "infrastructure",
      "kubernetes",
      "architecture"
    ]
  },
  {
    "title": "쿠브플로우를 설치하는 다양한 방법",
    "path": "/docs/machine-learning/platforms/install-kubeflow",
    "description": "Install Kubeflow",
    "tags": [
      "machine-learning",
      "mlops",
      "kubeflow",
      "installation",
      "tutorial"
    ],
    "keywords": [
      "machine",
      "learning",
      "platforms",
      "install",
      "kubeflow"
    ]
  },
  {
    "title": "타르(tar) 파일 설치하기",
    "path": "/docs/foundations/linux/install-tar-gz",
    "description": "Install Tar.Gz",
    "tags": [
      "linux",
      "package-management",
      "tutorial"
    ],
    "keywords": [
      "foundations",
      "linux",
      "install",
      "tar",
      "gz"
    ]
  },
  {
    "title": "테이블 방법을 통한 계획과 학습",
    "path": "/docs/ml/reinforcement-learning/planning-and-learning-tabular-methods",
    "description": "Planning and Learning with Tabular Methods",
    "tags": [
      "ml",
      "rl"
    ],
    "keywords": [
      "ml",
      "reinforcement",
      "learning",
      "planning",
      "and",
      "tabular",
      "methods"
    ]
  },
  {
    "title": "통합설계",
    "path": "/docs/cs/digital-system-design-methodology/cosim",
    "description": "디지털 시스템 설계방법론 - 통합설계",
    "tags": [
      "cs"
    ],
    "keywords": [
      "cs",
      "digital",
      "system",
      "design",
      "methodology",
      "cosim"
    ]
  },
  {
    "title": "평가 지표",
    "path": "/docs/ml/general/evaluation-metric",
    "description": "Evaluation Metric",
    "tags": [
      "general",
      "ml"
    ],
    "keywords": [
      "ml",
      "general",
      "evaluation",
      "metric"
    ]
  },
  {
    "title": "학습에 중요한 데이터 찾기",
    "path": "/docs/machine-learning/research-papers/deep-learning-on-a-data-diet",
    "description": "학습에 중요한 데이터 찾기",
    "tags": [
      "machine-learning",
      "deep-learning",
      "data-efficiency",
      "research"
    ],
    "keywords": [
      "machine",
      "learning",
      "research",
      "papers",
      "deep",
      "on",
      "a",
      "data",
      "diet"
    ]
  },
  {
    "title": "확률",
    "path": "/docs/ml/machine-learning/probability",
    "description": "기본적인 확률 이론에 대해서",
    "tags": [
      "math",
      "machine learning"
    ],
    "keywords": [
      "ml",
      "machine",
      "learning",
      "probability"
    ]
  },
  {
    "title": "확장형 고성능 컴퓨팅 소개",
    "path": "/docs/cs/high-performance-computing/introduction",
    "description": "확장가능한 프로그래밍",
    "tags": [
      "cs"
    ],
    "keywords": [
      "cs",
      "high",
      "performance",
      "computing",
      "introduction"
    ]
  },
  {
    "title": "Agile",
    "path": "/docs/development/practices/agile",
    "description": "애자일",
    "tags": [
      "methodology",
      "agile",
      "best-practices"
    ],
    "keywords": [
      "development",
      "practices",
      "agile"
    ]
  },
  {
    "title": "Alphapose 논문 리뷰와 사용",
    "path": "/docs/machine-learning/computer-vision/alphapose",
    "description": "Alphapose 논문 리뷰와 사용",
    "tags": [
      "machine-learning",
      "computer-vision",
      "pose-estimation"
    ],
    "keywords": [
      "machine",
      "learning",
      "computer",
      "vision",
      "alphapose"
    ]
  },
  {
    "title": "Attention 다시보기",
    "path": "/docs/machine-learning/deep-learning/attention-is-all-you-need",
    "description": "Attention is all you need",
    "tags": [
      "machine-learning",
      "deep-learning",
      "transformers",
      "research"
    ],
    "keywords": [
      "machine",
      "learning",
      "deep",
      "attention",
      "is",
      "all",
      "you",
      "need"
    ]
  },
  {
    "title": "Build OpenCV with Java",
    "path": "/docs/development/languages/build-opencv-with-java",
    "description": "OpenCV 자바로 빌드하기",
    "tags": [
      "java",
      "opencv",
      "computer-vision",
      "tutorial"
    ],
    "keywords": [
      "development",
      "languages",
      "build",
      "opencv",
      "with",
      "java"
    ]
  },
  {
    "title": "DDPM: Denoising Diffusion Probabilistic Models",
    "path": "/docs/ml/deep-learning-papers/ddpm",
    "description": "노이즈를 단계적으로 제거해 데이터를 생성하는 Diffusion 모델",
    "tags": [
      "deep learning",
      "generative model",
      "diffusion",
      "ddpm"
    ],
    "keywords": [
      "ml",
      "deep",
      "learning",
      "papers",
      "ddpm"
    ]
  },
  {
    "title": "Deploying Ml Model On Kubernetes Nuclio",
    "path": "/docs/infrastructure/tools/deploying-ml-model-nuclio",
    "description": "쿠버네티스 누클리오에 ML 모델 배포하기",
    "tags": [
      "kubernetes",
      "machine-learning",
      "serverless",
      "deployment"
    ],
    "keywords": [
      "infrastructure",
      "tools",
      "deploying",
      "ml",
      "model",
      "nuclio"
    ]
  },
  {
    "title": "Dex",
    "path": "/docs/infrastructure/kubernetes/dex",
    "description": "Dex: OpenID 커넥터",
    "tags": [
      "kubernetes",
      "security",
      "authentication"
    ],
    "keywords": [
      "infrastructure",
      "kubernetes",
      "dex"
    ]
  },
  {
    "title": "Docker Shared Volume",
    "path": "/docs/infrastructure/containerization/docker-shared-volume",
    "description": "도커 컨테이너와 공유 볼륨",
    "tags": [
      "docker",
      "containerization",
      "storage",
      "quick-reference"
    ],
    "keywords": [
      "infrastructure",
      "containerization",
      "docker",
      "shared",
      "volume"
    ]
  },
  {
    "title": "Ensemble Methods",
    "path": "/docs/machine-learning/fundamentals/ensemble-methods",
    "description": "Ensemble Methods",
    "tags": [
      "machine-learning",
      "ensemble",
      "theory"
    ],
    "keywords": [
      "machine",
      "learning",
      "fundamentals",
      "ensemble",
      "methods"
    ]
  },
  {
    "title": "Envoy",
    "path": "/docs/infrastructure/kubernetes/envoy",
    "description": "Envoy proxy: 대규모 서비스를 위한 L7 프록시",
    "tags": [
      "kubernetes",
      "service-mesh",
      "networking"
    ],
    "keywords": [
      "infrastructure",
      "kubernetes",
      "envoy"
    ]
  },
  {
    "title": "Faster R-CNN",
    "path": "/docs/ml/embedded-deep-learning/object-detection-networks/faster-rcnn",
    "description": "Faster R-CNN",
    "tags": [
      "cs",
      "ml"
    ],
    "keywords": [
      "ml",
      "embedded",
      "deep",
      "learning",
      "object",
      "detection",
      "networks",
      "faster",
      "rcnn"
    ]
  },
  {
    "title": "GANs: Generative Adversarial Networks",
    "path": "/docs/ml/deep-learning-papers/gans",
    "description": "Generator와 Discriminator의 적대적 학습으로 데이터를 생성하는 GAN",
    "tags": [
      "deep learning",
      "generative model",
      "gan"
    ],
    "keywords": [
      "ml",
      "deep",
      "learning",
      "papers",
      "gans"
    ]
  },
  {
    "title": "Github Issue",
    "path": "/docs/development/practices/github-issue",
    "description": "깃허브 이슈로 협업하기",
    "tags": [
      "git",
      "github",
      "workflow",
      "best-practices"
    ],
    "keywords": [
      "development",
      "practices",
      "github",
      "issue"
    ]
  },
  {
    "title": "Golang Setup",
    "path": "/docs/development/languages/golang-setup",
    "description": "고(Golang) 개발환경 구축하기",
    "tags": [
      "go",
      "golang",
      "setup",
      "tutorial"
    ],
    "keywords": [
      "development",
      "languages",
      "golang",
      "setup"
    ]
  },
  {
    "title": "GPT: Improving Language Understanding by Generative Pre-Training",
    "path": "/docs/ml/deep-learning-papers/gpt",
    "description": "언어 모델 사전학습으로 GPT 시리즈의 시작을 연 논문",
    "tags": [
      "deep learning",
      "nlp",
      "transformer",
      "gpt",
      "pretraining"
    ],
    "keywords": [
      "ml",
      "deep",
      "learning",
      "papers",
      "gpt"
    ]
  },
  {
    "title": "Gradient",
    "path": "/docs/ml/general/gradient",
    "description": "Gradient",
    "tags": [],
    "keywords": [
      "ml",
      "general",
      "gradient"
    ]
  },
  {
    "title": "GUI 없이 버추얼박스 사용하기",
    "path": "/docs/foundations/linux/virtualbox-with-no-gui",
    "description": "Virtualbox With No Gui",
    "tags": [
      "linux",
      "virtualization",
      "tutorial"
    ],
    "keywords": [
      "foundations",
      "linux",
      "virtualbox",
      "with",
      "no",
      "gui"
    ]
  },
  {
    "title": "Information Theory",
    "path": "/docs/foundations/mathematics/information-theory",
    "description": "정보 이론",
    "tags": [
      "mathematics",
      "information-theory",
      "theory"
    ],
    "keywords": [
      "foundations",
      "mathematics",
      "information",
      "theory"
    ]
  },
  {
    "title": "Install Harbor",
    "path": "/docs/infrastructure/tools/install-harbor",
    "description": "쿠버네티스에 Harbor 설치하기",
    "tags": [
      "kubernetes",
      "registry",
      "installation",
      "tutorial"
    ],
    "keywords": [
      "infrastructure",
      "tools",
      "install",
      "harbor"
    ]
  },
  {
    "title": "Install Helm",
    "path": "/docs/infrastructure/tools/install-helm",
    "description": "Helm: 쿠버네티스 패키지 매니저",
    "tags": [
      "kubernetes",
      "helm",
      "installation",
      "tutorial"
    ],
    "keywords": [
      "infrastructure",
      "tools",
      "install",
      "helm"
    ]
  },
  {
    "title": "Intelligent Computer Vision 1",
    "path": "/docs/machine-learning/computer-vision/intelligent-cv-fundamentals",
    "description": "Intelligent Computer Vision 1(개요)",
    "tags": [
      "machine-learning",
      "computer-vision",
      "lecture"
    ],
    "keywords": [
      "machine",
      "learning",
      "computer",
      "vision",
      "intelligent",
      "cv",
      "fundamentals"
    ]
  },
  {
    "title": "Istio",
    "path": "/docs/infrastructure/kubernetes/istio",
    "description": "Istio: 서비스 메시",
    "tags": [
      "kubernetes",
      "service-mesh",
      "networking"
    ],
    "keywords": [
      "infrastructure",
      "kubernetes",
      "istio"
    ]
  },
  {
    "title": "K8S Tip Configmap",
    "path": "/docs/infrastructure/kubernetes/configmap",
    "description": "K8s tip: ConfigMap",
    "tags": [
      "kubernetes",
      "configuration",
      "quick-reference"
    ],
    "keywords": [
      "infrastructure",
      "kubernetes",
      "configmap"
    ]
  },
  {
    "title": "K8S Tip Expose Service",
    "path": "/docs/infrastructure/kubernetes/expose-service",
    "description": "K8s tip: Expose Service",
    "tags": [
      "kubernetes",
      "networking",
      "quick-reference"
    ],
    "keywords": [
      "infrastructure",
      "kubernetes",
      "expose",
      "service"
    ]
  },
  {
    "title": "K8S Tip Nodeselector",
    "path": "/docs/infrastructure/kubernetes/nodeselector",
    "description": "K8s tip: nodeSelector",
    "tags": [
      "kubernetes",
      "scheduling",
      "quick-reference"
    ],
    "keywords": [
      "infrastructure",
      "kubernetes",
      "nodeselector"
    ]
  },
  {
    "title": "K8S Tip Pv Terminating",
    "path": "/docs/infrastructure/kubernetes/pv-terminating",
    "description": "K8s tip: PersistentVolume terminating",
    "tags": [
      "kubernetes",
      "storage",
      "troubleshooting"
    ],
    "keywords": [
      "infrastructure",
      "kubernetes",
      "pv",
      "terminating"
    ]
  },
  {
    "title": "K8S Tip Rollback",
    "path": "/docs/infrastructure/kubernetes/rollback",
    "description": "K8s tip: Rollback",
    "tags": [
      "kubernetes",
      "deployment",
      "quick-reference"
    ],
    "keywords": [
      "infrastructure",
      "kubernetes",
      "rollback"
    ]
  },
  {
    "title": "Kubeflow Guide",
    "path": "/docs/machine-learning/platforms/kubeflow-guide",
    "description": "쿠브플로우 가이드",
    "tags": [
      "machine-learning",
      "mlops",
      "kubeflow",
      "tutorial"
    ],
    "keywords": [
      "machine",
      "learning",
      "platforms",
      "kubeflow",
      "guide"
    ]
  },
  {
    "title": "Kubeflow Visualization 1",
    "path": "/docs/machine-learning/platforms/kubeflow-visualization-1",
    "description": "Kubeflow 시각화 개발 1편",
    "tags": [
      "machine-learning",
      "mlops",
      "kubeflow",
      "visualization"
    ],
    "keywords": [
      "machine",
      "learning",
      "platforms",
      "kubeflow",
      "visualization",
      "1"
    ]
  },
  {
    "title": "Kubeflow Visualization 2",
    "path": "/docs/machine-learning/platforms/kubeflow-visualization-2",
    "description": "Kubeflow 시각화 개발 2편",
    "tags": [
      "machine-learning",
      "mlops",
      "kubeflow",
      "visualization"
    ],
    "keywords": [
      "machine",
      "learning",
      "platforms",
      "kubeflow",
      "visualization",
      "2"
    ]
  },
  {
    "title": "Linux Disk Free",
    "path": "/docs/foundations/linux/linux-disk-free",
    "description": "리눅스 디스크 정리하기",
    "tags": [
      "linux",
      "disk-management",
      "quick-reference"
    ],
    "keywords": [
      "foundations",
      "linux",
      "disk",
      "free"
    ]
  },
  {
    "title": "LLaMa 공개된 효율적인 언어 모델",
    "path": "/docs/machine-learning/research-papers/llama-foundation-models",
    "description": "LLaMA: Open and Efficient Foundation Language Models",
    "tags": [
      "machine-learning",
      "deep-learning",
      "llm",
      "research"
    ],
    "keywords": [
      "machine",
      "learning",
      "research",
      "papers",
      "llama",
      "foundation",
      "models"
    ]
  },
  {
    "title": "LoRA: Low-Rank Adaptation of Large Language Models",
    "path": "/docs/ml/deep-learning-papers/lora",
    "description": "대형 모델을 저랭크 행렬 분해로 효율적으로 파인튜닝하는 기법",
    "tags": [
      "deep learning",
      "fine-tuning",
      "lora",
      "peft",
      "llm"
    ],
    "keywords": [
      "ml",
      "deep",
      "learning",
      "papers",
      "lora"
    ]
  },
  {
    "title": "Low-power Image Recognition Challenge",
    "path": "/docs/ml/embedded-deep-learning/object-detection-networks/lpirc",
    "description": "LPIRC에서 우승하는 방법",
    "tags": [
      "cs",
      "ml"
    ],
    "keywords": [
      "ml",
      "embedded",
      "deep",
      "learning",
      "object",
      "detection",
      "networks",
      "lpirc"
    ]
  },
  {
    "title": "Minio",
    "path": "/docs/infrastructure/tools/minio",
    "description": "minIO 오브젝트 스토리지",
    "tags": [
      "kubernetes",
      "storage",
      "object-storage"
    ],
    "keywords": [
      "infrastructure",
      "tools",
      "minio"
    ]
  },
  {
    "title": "n-단계 부트스트래핑",
    "path": "/docs/ml/reinforcement-learning/n-step-bootstrapping",
    "description": "n-step Bootstrapping",
    "tags": [
      "ml",
      "rl"
    ],
    "keywords": [
      "ml",
      "reinforcement",
      "learning",
      "n",
      "step",
      "bootstrapping"
    ]
  },
  {
    "title": "NGRX 반응형 웹을 위한 상태 관리",
    "path": "/docs/development/web/ngrx",
    "description": "NGRX",
    "tags": [
      "typescript",
      "web",
      "state-management",
      "angular"
    ],
    "keywords": [
      "development",
      "web",
      "ngrx"
    ]
  },
  {
    "title": "Nuclio 개념과 아키텍처",
    "path": "/docs/infrastructure/tools/nuclio",
    "description": "Automate the Data Science Pipeline with Serverless Functions",
    "tags": [
      "kubernetes",
      "serverless",
      "tutorial"
    ],
    "keywords": [
      "infrastructure",
      "tools",
      "nuclio"
    ]
  },
  {
    "title": "Nvidia GPU 아키텍처",
    "path": "/docs/foundations/computer-architecture/nvidia-gpu-arch",
    "description": "Nvidia GPU Architectures",
    "tags": [
      "hardware",
      "gpu",
      "architecture"
    ],
    "keywords": [
      "foundations",
      "computer",
      "architecture",
      "nvidia",
      "gpu",
      "arch"
    ]
  },
  {
    "title": "Pathways를 이용한 언어모델 스케일링",
    "path": "/docs/machine-learning/research-papers/palm-scaling-language-modeling",
    "description": "PaLM: Scaling Language Modeling with Pathways",
    "tags": [
      "machine-learning",
      "deep-learning",
      "llm",
      "research"
    ],
    "keywords": [
      "machine",
      "learning",
      "research",
      "papers",
      "palm",
      "scaling",
      "language",
      "modeling"
    ]
  },
  {
    "title": "PEFT: Parameter-Efficient Fine-Tuning",
    "path": "/docs/ml/deep-learning-papers/peft",
    "description": "대형 모델의 파라미터 일부만 학습하는 효율적 파인튜닝 기법 모음",
    "tags": [
      "deep learning",
      "fine-tuning",
      "peft",
      "lora",
      "llm"
    ],
    "keywords": [
      "ml",
      "deep",
      "learning",
      "papers",
      "peft"
    ]
  },
  {
    "title": "RAG: Retrieval-Augmented Generation",
    "path": "/docs/ml/deep-learning-papers/rag",
    "description": "외부 문서 검색을 결합해 LLM의 지식을 확장하는 RAG 기법",
    "tags": [
      "deep learning",
      "nlp",
      "rag",
      "llm",
      "retrieval"
    ],
    "keywords": [
      "ml",
      "deep",
      "learning",
      "papers",
      "rag"
    ]
  },
  {
    "title": "RISC 컴퓨터를 위한 사례",
    "path": "/docs/machine-learning/deep-learning/risc-for-ml",
    "description": "The Case for the Reduced Instruction Set Computer",
    "tags": [
      "machine-learning",
      "hardware",
      "architecture",
      "research"
    ],
    "keywords": [
      "machine",
      "learning",
      "deep",
      "risc",
      "for",
      "ml"
    ]
  },
  {
    "title": "RISC V 명령어 셋 아키텍처",
    "path": "/docs/foundations/computer-architecture/risc-v-isa",
    "description": "RISC V Instruction Set Architecture",
    "tags": [
      "cs",
      "computer architecture"
    ],
    "keywords": [
      "foundations",
      "computer",
      "architecture",
      "risc",
      "v",
      "isa"
    ]
  },
  {
    "title": "Sagemaker",
    "path": "/docs/machine-learning/platforms/sagemaker",
    "description": "아마존 세이지메이커: 머신러닝 자동화",
    "tags": [
      "machine-learning",
      "mlops",
      "aws",
      "sagemaker"
    ],
    "keywords": [
      "machine",
      "learning",
      "platforms",
      "sagemaker"
    ]
  },
  {
    "title": "Single Shot Detector",
    "path": "/docs/ml/embedded-deep-learning/object-detection-networks/ssd",
    "description": "Single Shot Detector",
    "tags": [
      "cs",
      "ml"
    ],
    "keywords": [
      "ml",
      "embedded",
      "deep",
      "learning",
      "object",
      "detection",
      "networks",
      "ssd"
    ]
  },
  {
    "title": "Uncertainty Estimation",
    "path": "/docs/machine-learning/fundamentals/uncertainty-estimation",
    "description": "Uncertainty Estimation",
    "tags": [
      "machine-learning",
      "uncertainty",
      "theory"
    ],
    "keywords": [
      "machine",
      "learning",
      "fundamentals",
      "uncertainty",
      "estimation"
    ]
  },
  {
    "title": "Uuid",
    "path": "/docs/foundations/linux/uuid",
    "description": "UUID 범용 고유 식별자",
    "tags": [
      "linux",
      "system",
      "quick-reference"
    ],
    "keywords": [
      "foundations",
      "linux",
      "uuid"
    ]
  },
  {
    "title": "Variable Autoencoder",
    "path": "/docs/machine-learning/research-papers/variable-autoencoder",
    "description": "VAE: Variable Auto Encoder",
    "tags": [
      "machine-learning",
      "deep-learning",
      "vae",
      "research"
    ],
    "keywords": [
      "machine",
      "learning",
      "research",
      "papers",
      "variable",
      "autoencoder"
    ]
  },
  {
    "title": "ViT: An Image is Worth 16x16 Words",
    "path": "/docs/ml/deep-learning-papers/vit",
    "description": "이미지를 패치로 분할해 Transformer를 비전에 적용한 논문",
    "tags": [
      "deep learning",
      "vision",
      "transformer",
      "image classification"
    ],
    "keywords": [
      "ml",
      "deep",
      "learning",
      "papers",
      "vit"
    ]
  },
  {
    "title": "Welcome To Docker",
    "path": "/docs/infrastructure/containerization/welcome-to-docker",
    "description": "도커의 세계에 오신 걸 환영합니다!",
    "tags": [
      "docker",
      "containerization",
      "introduction"
    ],
    "keywords": [
      "infrastructure",
      "containerization",
      "welcome",
      "to",
      "docker"
    ]
  },
  {
    "title": "Welcome To Kubeflow",
    "path": "/docs/machine-learning/platforms/welcome-to-kubeflow",
    "description": "쿠브플로우: 머신러닝 자동화",
    "tags": [
      "machine-learning",
      "mlops",
      "kubeflow",
      "introduction"
    ],
    "keywords": [
      "machine",
      "learning",
      "platforms",
      "welcome",
      "to",
      "kubeflow"
    ]
  },
  {
    "title": "You Only Look Once",
    "path": "/docs/ml/embedded-deep-learning/object-detection-networks/yolo",
    "description": "You Only Look Once",
    "tags": [
      "cs",
      "ml"
    ],
    "keywords": [
      "ml",
      "embedded",
      "deep",
      "learning",
      "object",
      "detection",
      "networks",
      "yolo"
    ]
  }
];
