// AUTO-GENERATED by scripts/fetch-ga-views.js
// Run `node scripts/fetch-ga-views.js` locally or configure CI secrets to update.
// Empty array = GA4 not configured; landing page falls back to recent posts.

export type GaView = {
  path: string;
  views: number;
};

export const GA_VIEWS: GaView[] = [];

// Format: 'YYYY. MM' (e.g. '2026. 06'), empty string if GA4 not configured
export const GA_UPDATED_AT: string = '';