name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm #yarn

      - name: Install dependencies
        run: npm ci #yarn install --frozen-lockfile
      - name: Build website
        run: npm run build #yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build
          # user_name: github-actions[bot]
          # user_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Copy google site verification
        uses: actions/checkout@v2
        env:
          TARGET_BRANCH: 'gh-pages'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch
          git checkout $TARGET_BRANCH
          git checkout docusaurus -- google2f0d0a0c841af853.html
          git add -A
          git push origin $TARGET_BRANCH